import { readFileSync } from 'node:fs'
import { basename } from 'node:path'
import ts from 'typescript'
import { HAPI_PLUGIN_API_VERSION } from '../../shared/src/plugins'
import { bundledExamplePlugins } from '../../shared/src/plugins/bundledExamples'
import type { EndpointDoc } from './endpointCatalog'
import type { SchemaDoc, SchemaGroup } from './schemaCatalog'

export const GENERATED_HEADER = '<!-- AUTO-GENERATED by scripts/generate-plugin-api-docs.ts. DO NOT EDIT. -->\n\n'

export type JsonSchema = Record<string, unknown>

export type SchemaRenderInput = {
    doc: SchemaDoc
    jsonSchema: JsonSchema
    publicPath: string
}

export type SdkDeclaration = {
    name: string
    kind: 'type' | 'interface'
    summary: string
    source: string
}

const groupLabels: Record<SchemaGroup, string> = {
    manifest: 'Manifest',
    admin: 'Admin API',
    runtime: 'Hub runtime',
    runner: 'Runner runtime',
    agent: 'Agent extensions',
    web: 'Web descriptors',
    state: 'State files'
}

export function schemaPublicPath(id: string): string {
    return `/docs/plugin-api/schemas/${id}.schema.json`
}

export function markdownSchemaLink(doc: SchemaDoc): string {
    return `[${doc.title}](${schemaPublicPath(doc.id)})`
}

export function jsonBlock(value: unknown): string {
    return `\n\`\`\`json\n${JSON.stringify(value, null, 4)}\n\`\`\`\n`
}

function tsBlock(source: string): string {
    return `\n\`\`\`ts\n${source.trim()}\n\`\`\`\n`
}

function shellBlock(source: string): string {
    return `\n\`\`\`bash\n${source.trim()}\n\`\`\`\n`
}

function getProperties(schema: JsonSchema): Record<string, JsonSchema> {
    const properties = schema.properties
    if (!properties || typeof properties !== 'object' || Array.isArray(properties)) return {}
    return properties as Record<string, JsonSchema>
}

function getRequired(schema: JsonSchema): Set<string> {
    const required = schema.required
    if (!Array.isArray(required)) return new Set()
    return new Set(required.filter((entry): entry is string => typeof entry === 'string'))
}

function describeType(schema: JsonSchema): string {
    if (typeof schema.const === 'string' || typeof schema.const === 'number' || typeof schema.const === 'boolean') {
        return `const \`${String(schema.const)}\``
    }
    if (Array.isArray(schema.enum)) {
        return schema.enum.map((entry) => `\`${String(entry)}\``).join(' | ')
    }
    if (typeof schema.type === 'string') {
        if (schema.type === 'array' && schema.items && typeof schema.items === 'object') {
            return `array<${describeType(schema.items as JsonSchema)}>`
        }
        return schema.type
    }
    if (Array.isArray(schema.type)) {
        return schema.type.map(String).join(' | ')
    }
    if (Array.isArray(schema.anyOf)) return schema.anyOf.map((entry) => describeType(entry as JsonSchema)).join(' | ')
    if (Array.isArray(schema.oneOf)) return schema.oneOf.map((entry) => describeType(entry as JsonSchema)).join(' | ')
    return 'object'
}

function renderPropertiesTable(input: SchemaRenderInput): string {
    const properties = getProperties(input.jsonSchema)
    const names = Object.keys(properties)
    if (names.length === 0) return ''
    const required = getRequired(input.jsonSchema)
    const rows = names.map((name) => {
        const property = properties[name] ?? {}
        const description = typeof property.description === 'string' ? property.description : ''
        return `| \`${escapeTableCell(name)}\` | ${required.has(name) ? 'yes' : 'no'} | ${escapeTableCell(describeType(property))} | ${escapeTableCell(description || '—')} |`
    })
    return [
        '## Top-level fields',
        '',
        '| Field | Required | Type | Notes |',
        '|---|---|---|---|',
        ...rows,
        ''
    ].join('\n')
}

function escapeTableCell(value: string): string {
    return value
        .replace(/\\|/g, '\\\\|')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;')
}

function renderSchemaPage(input: SchemaRenderInput): string {
    return GENERATED_HEADER + [
        `# ${input.doc.title}`,
        '',
        input.doc.description,
        '',
        `Group: **${groupLabels[input.doc.group]}**`,
        '',
        `JSON Schema: ${markdownSchemaLink(input.doc)}`,
        '',
        renderPropertiesTable(input),
        '## JSON Schema',
        jsonBlock(input.jsonSchema)
    ].filter(Boolean).join('\n')
}

export function renderSchemasIndex(inputs: SchemaRenderInput[]): string {
    const groups = [...new Set(inputs.map((input) => input.doc.group))]
    const sections = groups.map((group) => {
        const rows = inputs
            .filter((input) => input.doc.group === group)
            .map((input) => `| ${markdownSchemaLink(input.doc)} | ${input.doc.description} |`)
        return [
            `## ${groupLabels[group]}`,
            '',
            '| Schema | Description |',
            '|---|---|',
            ...rows,
            ''
        ].join('\n')
    })

    return GENERATED_HEADER + [
        '# Plugin API schemas',
        '',
        'Generated from Zod schemas under `shared/src/plugins/*`.',
        '',
        ...sections
    ].join('\n')
}

export function renderIndex(inputs: SchemaRenderInput[]): string {
    const manifest = inputs.find((input) => input.doc.title === 'PluginManifestLite')
    const count = inputs.length
    return GENERATED_HEADER + [
        '# Plugin API reference',
        '',
        `Plugin API version: \`${HAPI_PLUGIN_API_VERSION}\``,
        '',
        `Generated schema count: **${count}**`,
        '',
        'This section is generated from the repo source. Edit TypeScript/Zod sources, then run:',
        shellBlock('bun run docs:plugin-api'),
        'Check mode for CI:',
        shellBlock('bun run docs:plugin-api:check'),
        '## Primary surfaces',
        '',
        '- [Tutorials](./tutorial.md) — step-by-step plugin development guides.',
        '- [Manifest](./manifest.md) — cold-path `hapi.plugin.json` contract.',
        '- [Runtime SDK](./runtime-sdk.md) — public TypeScript types exported from `@hapi/protocol/plugins`.',
        '- [Hub runtime](./hub-runtime.md) — notification channel runtime.',
        '- [Runner runtime](./runner-runtime.md) — environment, command, spawn, agent adapter hooks.',
        '- [Web descriptors](./web-descriptors.md) — declarative UI descriptors, no plugin JS in Web.',
        '- [Agent extensions](./agent-extensions.md) — plugin-backed agent adapter and capability provider contracts.',
        '- [Admin REST API](./admin-rest-api.md) — authenticated management endpoints.',
        '- [Schemas](./schemas.md) — all generated JSON Schemas.',
        '',
        manifest ? `Manifest JSON Schema: ${markdownSchemaLink(manifest.doc)}` : ''
    ].filter(Boolean).join('\n')
}

export function renderManifestPage(inputs: SchemaRenderInput[]): string {
    const manifest = requireSchemaInput(inputs, 'PluginManifestLite')
    const example = bundledExamplePlugins[0]?.manifest
    return GENERATED_HEADER + [
        '# Plugin manifest',
        '',
        '`hapi.plugin.json` is the cold-path plugin contract. HAPI validates it before importing any runtime entry.',
        '',
        `Supported plugin API version: \`${HAPI_PLUGIN_API_VERSION}\``,
        '',
        renderPropertiesTable(manifest),
        '## Minimal example',
        example ? jsonBlock(example) : '',
        '## JSON Schema',
        `Download: ${markdownSchemaLink(manifest.doc)}`,
        jsonBlock(manifest.jsonSchema)
    ].filter(Boolean).join('\n')
}

export function extractSdkDeclarations(sdkFilePath: string): SdkDeclaration[] {
    const source = readFileSync(sdkFilePath, 'utf8')
    const sourceFile = ts.createSourceFile(sdkFilePath, source, ts.ScriptTarget.Latest, true, ts.ScriptKind.TS)
    const declarations: SdkDeclaration[] = []

    for (const statement of sourceFile.statements) {
        if (!isExported(statement)) continue
        if (!ts.isTypeAliasDeclaration(statement) && !ts.isInterfaceDeclaration(statement)) continue
        const name = statement.name.text
        const kind = ts.isInterfaceDeclaration(statement) ? 'interface' : 'type'
        const summary = getJsDocSummary(source, statement) || 'Public plugin SDK type.'
        declarations.push({
            name,
            kind,
            summary,
            source: source.slice(statement.getStart(sourceFile), statement.end)
        })
    }

    return declarations
}

function isExported(node: ts.Node): boolean {
    return Boolean(ts.getCombinedModifierFlags(node as ts.Declaration) & ts.ModifierFlags.Export)
}

function getJsDocSummary(source: string, node: ts.Node): string {
    const ranges = ts.getLeadingCommentRanges(source, node.pos) ?? []
    const jsDoc = ranges
        .map((range) => source.slice(range.pos, range.end))
        .find((comment) => comment.startsWith('/**'))
    if (!jsDoc) return ''
    return jsDoc
        .replace(/^\/\*\*/, '')
        .replace(/\*\/$/, '')
        .split('\n')
        .map((line) => line.replace(/^\s*\* ?/, '').trim())
        .filter(Boolean)
        .join(' ')
}

function renderDeclarationList(declarations: SdkDeclaration[], names: string[]): string {
    return names.map((name) => {
        const declaration = declarations.find((entry) => entry.name === name)
        if (!declaration) return `### ${name}\n\n_Missing from generated SDK declarations._\n`
        return [`### ${declaration.name}`, '', declaration.summary, tsBlock(declaration.source)].join('\n')
    }).join('\n')
}

export function renderRuntimeSdkPage(declarations: SdkDeclaration[]): string {
    return GENERATED_HEADER + [
        '# Runtime SDK types',
        '',
        'Generated from `shared/src/plugins/sdk.ts`. Plugin runtimes should import public types from `@hapi/protocol/plugins`.',
        tsBlock("import type { HubPluginContext, RunnerPluginContext } from '@hapi/protocol/plugins'"),
        '## Common runtime primitives',
        '',
        renderDeclarationList(declarations, [
            'MaybePromise',
            'Disposable',
            'PluginLogger',
            'PluginConfigReader',
            'PluginSecretReader'
        ]),
        '## Hub runtime',
        '',
        renderDeclarationList(declarations, [
            'PluginNotificationChannel',
            'HubPluginContext',
            'HubPluginModule'
        ]),
        '## Runner runtime',
        '',
        renderDeclarationList(declarations, [
            'RunnerPluginContext',
            'RunnerEnvironmentProviderContribution',
            'RunnerCommandResolverContribution',
            'RunnerSpawnHookContribution',
            'RunnerAgentAdapterContribution',
            'RunnerAgentCapabilityProviderContribution'
        ]),
        '## Plugin-backed agent backend',
        '',
        renderDeclarationList(declarations, [
            'AgentBackend',
            'AgentBackendFactory',
            'AgentMessage',
            'PermissionRequest',
            'PermissionResponse'
        ])
    ].join('\n')
}

export function renderHubRuntimePage(inputs: SchemaRenderInput[], declarations: SdkDeclaration[]): string {
    const notification = requireSchemaInput(inputs, 'PluginNotificationEvent')
    return GENERATED_HEADER + [
        '# Hub runtime',
        '',
        'Hub plugins run as trusted local in-process code on the Hub machine. Current public Hub extension point: notification channels.',
        '',
        '## SDK types',
        '',
        renderDeclarationList(declarations, ['HubPluginContext', 'PluginNotificationChannel', 'HubPluginModule']),
        '## Notification event schema',
        '',
        notification.doc.description,
        '',
        `JSON Schema: ${markdownSchemaLink(notification.doc)}`,
        jsonBlock(notification.jsonSchema)
    ].join('\n')
}

export function renderRunnerRuntimePage(inputs: SchemaRenderInput[], declarations: SdkDeclaration[]): string {
    const names = [
        'RunnerSpawnContext',
        'RunnerEnvironmentProposal',
        'RunnerCommandResolverProposal',
        'RunnerSpawnHookProposal',
        'RunnerResolvedSpawnPlan'
    ]
    const schemaSections = names.map((name) => renderSchemaBrief(requireSchemaInput(inputs, name))).join('\n')
    return GENERATED_HEADER + [
        '# Runner runtime',
        '',
        'Runner plugins run as trusted local in-process code on the Runner machine. Core keeps final command/session lifecycle control.',
        '',
        '## SDK types',
        '',
        renderDeclarationList(declarations, [
            'RunnerPluginContext',
            'RunnerEnvironmentProviderContribution',
            'RunnerCommandResolverContribution',
            'RunnerSpawnHookContribution'
        ]),
        '## Runtime schemas',
        '',
        schemaSections
    ].join('\n')
}

export function renderWebDescriptorsPage(inputs: SchemaRenderInput[]): string {
    const web = requireSchemaInput(inputs, 'PluginWebContributions')
    const example = bundledExamplePlugins.find((plugin) => plugin.manifest.contributions?.web)?.manifest.contributions?.web
    return GENERATED_HEADER + [
        '# Web descriptors',
        '',
        'Web contributions are declarative descriptors. The Web app renders validated JSON and never executes plugin JavaScript.',
        '',
        `JSON Schema: ${markdownSchemaLink(web.doc)}`,
        '',
        '## Example',
        example ? jsonBlock(example) : '',
        '## Schema',
        jsonBlock(web.jsonSchema)
    ].filter(Boolean).join('\n')
}

export function renderAgentExtensionsPage(inputs: SchemaRenderInput[], declarations: SdkDeclaration[]): string {
    const schemas = [
        'AgentDescriptor',
        'AgentCapabilityProviderResult',
        'AgentCapabilityProviderSnapshot',
        'AgentHistoryImportResult'
    ].map((name) => renderSchemaBrief(requireSchemaInput(inputs, name))).join('\n')
    return GENERATED_HEADER + [
        '# Agent extensions',
        '',
        'Agent adapter and capability provider plugins execute in the Runner runtime. Hub/Web consume validated descriptors and snapshots.',
        '',
        '## SDK types',
        '',
        renderDeclarationList(declarations, [
            'RunnerAgentAdapterContribution',
            'RunnerAgentCapabilityProviderContribution',
            'AgentBackend',
            'AgentBackendFactory',
            'AgentMessage'
        ]),
        '## Schemas',
        '',
        schemas
    ].join('\n')
}

export function renderAdminRestApiPage(endpoints: EndpointDoc[]): string {
    const rows = endpoints.map((endpoint) => {
        const body = endpoint.bodySchema ? `\`${endpoint.bodySchema}\`` : '—'
        return `| \`${endpoint.method}\` | \`${endpoint.path}\` | ${endpoint.targetQuery ? '`target`' : '—'} | ${body} | \`${endpoint.responseSchema}\` | ${endpoint.description} |`
    })
    return GENERATED_HEADER + [
        '# Plugin admin REST API',
        '',
        'Authenticated HAPI Web API endpoints for plugin management. `target` accepts `hub`, `runner:<machineId>`, or `all-runners` where supported.',
        '',
        'OpenAPI JSON: [/docs/plugin-api/openapi.json](/docs/plugin-api/openapi.json)',
        '',
        '| Method | Path | Query | Body | Response | Notes |',
        '|---|---|---|---|---|---|',
        ...rows,
        ''
    ].join('\n')
}

export function renderIndividualSchemaPages(inputs: SchemaRenderInput[]): Map<string, string> {
    const pages = new Map<string, string>()
    for (const input of inputs) {
        pages.set(`schemas/${input.doc.id}.md`, renderSchemaPage(input))
    }
    return pages
}

function renderSchemaBrief(input: SchemaRenderInput): string {
    return [
        `### ${input.doc.title}`,
        '',
        input.doc.description,
        '',
        `JSON Schema: ${markdownSchemaLink(input.doc)}`,
        '',
        renderPropertiesTable(input)
    ].join('\n')
}

function requireSchemaInput(inputs: SchemaRenderInput[], title: string): SchemaRenderInput {
    const match = inputs.find((input) => input.doc.title === title)
    if (!match) {
        throw new Error(`Missing schema render input: ${title}`)
    }
    return match
}

export function schemaGroupLabel(group: SchemaGroup): string {
    return groupLabels[group]
}

export function renderGeneratedFileList(files: string[]): string {
    return files.map((file) => `- ${basename(file)}`).join('\n')
}
