import { readFileSync } from 'node:fs'
import ts from 'typescript'
import { HAPI_PLUGIN_API_VERSION } from '../../shared/src/plugins'
import { bundledExamplePlugins } from '../../shared/src/plugins/bundledExamples'
import type { EndpointDoc, EndpointQueryParamDoc } from './endpointCatalog'
import type { SchemaDoc, SchemaGroup } from './schemaCatalog'

export const GENERATED_HEADER = '<!-- AUTO-GENERATED by scripts/generate-plugin-api-docs.ts. DO NOT EDIT. -->\n\n'

export type JsonSchema = Record<string, unknown>

export type SchemaRenderInput = {
    doc: SchemaDoc
    jsonSchema: JsonSchema
    publicPath: string
}

export type SdkDeclaration = {
    name: string
    kind: 'type' | 'interface'
    summary: string
    source: string
}

const groupLabels: Record<SchemaGroup, string> = {
    manifest: 'Manifest',
    admin: 'Admin API',
    runtime: 'Hub runtime',
    runner: 'Runner runtime',
    agent: 'Agent extensions',
    web: 'Web descriptors',
    state: 'State files',
    marketplace: 'Marketplace'
}

export function schemaPublicPath(id: string): string {
    return `/docs/plugin-api/schemas/${id}.schema.json`
}

export function markdownSchemaLink(doc: SchemaDoc): string {
    return `[${doc.title}](${schemaPublicPath(doc.id)})`
}

export function jsonBlock(value: unknown): string {
    const source = typeof value === 'string' ? value.trim() : JSON.stringify(value, null, 4)
    return `\n\`\`\`json\n${source}\n\`\`\`\n`
}

function codeBlock(language: string, source: string): string {
    return `\n\`\`\`${language}\n${source.trim()}\n\`\`\`\n`
}

function tsBlock(source: string): string {
    return codeBlock('ts', source)
}

function shellBlock(source: string): string {
    return codeBlock('bash', source)
}

function getProperties(schema: JsonSchema): Record<string, JsonSchema> {
    const properties = schema.properties
    if (!properties || typeof properties !== 'object' || Array.isArray(properties)) return {}
    return properties as Record<string, JsonSchema>
}

function getRequired(schema: JsonSchema): Set<string> {
    const required = schema.required
    if (!Array.isArray(required)) return new Set()
    return new Set(required.filter((entry): entry is string => typeof entry === 'string'))
}

function describeType(schema: JsonSchema): string {
    if (typeof schema.const === 'string' || typeof schema.const === 'number' || typeof schema.const === 'boolean') {
        return `const \`${String(schema.const)}\``
    }
    if (Array.isArray(schema.enum)) {
        return schema.enum.map((entry) => `\`${String(entry)}\``).join(' | ')
    }
    if (typeof schema.type === 'string') {
        if (schema.type === 'array' && schema.items && typeof schema.items === 'object') {
            return `array<${describeType(schema.items as JsonSchema)}>`
        }
        return schema.type
    }
    if (Array.isArray(schema.type)) {
        return schema.type.map(String).join(' | ')
    }
    if (Array.isArray(schema.anyOf)) return schema.anyOf.map((entry) => describeType(entry as JsonSchema)).join(' | ')
    if (Array.isArray(schema.oneOf)) return schema.oneOf.map((entry) => describeType(entry as JsonSchema)).join(' | ')
    if (schema.$ref && typeof schema.$ref === 'string') return schema.$ref.split('/').at(-1) ?? 'object'
    return 'object'
}

function renderPropertiesTable(input: SchemaRenderInput, heading = '## Top-level fields'): string {
    const properties = getProperties(input.jsonSchema)
    const names = Object.keys(properties)
    if (names.length === 0) return ''
    const required = getRequired(input.jsonSchema)
    const rows = names.map((name) => {
        const property = properties[name] ?? {}
        const description = typeof property.description === 'string' ? property.description : ''
        return `| \`${escapeTableCell(name)}\` | ${required.has(name) ? 'yes' : 'no'} | ${escapeTableCell(describeType(property))} | ${escapeTableCell(description || '—')} |`
    })
    return [
        heading,
        '',
        '| Field | Required | Type | Notes |',
        '|---|---|---|---|',
        ...rows,
        ''
    ].join('\n')
}

function escapeTableCell(value: string): string {
    return value
        .replace(/\|/g, '\\|')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;')
        .replace(/\n/g, '<br>')
}

function schemaLinkByTitle(inputs: SchemaRenderInput[], title: string): string {
    return markdownSchemaLink(requireSchemaInput(inputs, title).doc)
}

export function renderSchemasIndex(inputs: SchemaRenderInput[]): string {
    const groups = [...new Set(inputs.map((input) => input.doc.group))]
    const sections = groups.map((group) => {
        const rows = inputs
            .filter((input) => input.doc.group === group)
            .map((input) => `| ${markdownSchemaLink(input.doc)} | ${input.doc.description} |`)
        return [
            `## ${groupLabels[group]}`,
            '',
            '| JSON Schema | Description |',
            '|---|---|',
            ...rows,
            ''
        ].join('\n')
    })

    return GENERATED_HEADER + [
        '# Plugin API schemas',
        '',
        'Machine-readable JSON Schemas generated from Zod schemas under `shared/src/plugins/*`.',
        '',
        'The large schema bodies are intentionally published as JSON files only; human-facing pages link to them instead of duplicating thousands of generated Markdown lines.',
        '',
        ...sections
    ].join('\n')
}

export function renderIndex(inputs: SchemaRenderInput[]): string {
    return GENERATED_HEADER + [
        '# Plugin API reference',
        '',
        `Plugin API version: \`${HAPI_PLUGIN_API_VERSION}\``,
        '',
        'HAPI plugins are trusted local extension packages. Hub and Runner runtimes execute plugin JavaScript in-process; Web only renders validated descriptors and never loads plugin JavaScript.',
        '',
        '## Read path',
        '',
        '- [Quickstart](./quickstart.md) — minimal Hub, Runner, and descriptor-only examples.',
        '- [Manifest](./manifest.md) — `hapi.plugin.json` contract and placement rules.',
        '- [Runtimes](./runtimes.md) — Hub, Runner, and agent extension SDK surfaces.',
        '- [Web descriptors](./web-descriptors.md) — built-in UI primitives and descriptor examples.',
        '- [Admin API](./admin-api.md) — authenticated management endpoints and OpenAPI link.',
        '- [Marketplace](./marketplace.md) — static catalog and release-package flow.',
        '- [Schemas](./schemas.md) — generated JSON Schema links.',
        '',
        '## Safety model',
        '',
        '- Disabled or invalid runtime plugins are not imported.',
        '- Runtime entry paths must stay under the plugin root after `realpath`.',
        '- Secret values are read from environment variables through `ctx.secrets.get(name)` and must not be saved in `$HAPI_HOME/plugins.json`.',
        '- Hub/Runner plugin code is trusted local code, not sandboxed code.',
        '- Plugins cannot receive raw Store, SQLite, Socket.IO, SSE, or RPC gateway objects.',
        '',
        '## Runtime positions',
        '',
        '| Position | Executes plugin JS | Typical use |',
        '|---|---:|---|',
        '| Web | no | descriptor-only settings panels, composer actions, New Session fields |',
        '| Hub | yes | notification channels, chat composer message actions |',
        '| Runner | yes | spawn defaults, environment providers, command resolvers, hooks, agent adapters/actions |',
        '',
        `Manifest JSON Schema: ${schemaLinkByTitle(inputs, 'PluginManifestLite')}`
    ].join('\n')
}

export function renderManifestPage(inputs: SchemaRenderInput[]): string {
    const manifest = requireSchemaInput(inputs, 'PluginManifestLite')
    const example = bundledExamplePlugins[0]?.manifest
    return GENERATED_HEADER + [
        '# Plugin manifest',
        '',
        '`hapi.plugin.json` is the cold-path contract. HAPI validates it before importing any runtime entry.',
        '',
        `Supported plugin API version: \`${HAPI_PLUGIN_API_VERSION}\``,
        '',
        '## Placement rules',
        '',
        '- `contributions.web` or capability `parts.web`: installed on Hub, rendered by Web as descriptors.',
        '- `runtimes.hub`, `contributions.hub`, or capability `parts.hub`: requires Hub runtime placement.',
        '- `runtimes.runner`, `contributions.runner`, `contributions.agent`, or capability `parts.runner`: requires Runner placement.',
        '- A package may combine Web, Hub, and Runner parts; install-plan chooses compatible targets from the manifest.',
        '',
        renderPropertiesTable(manifest),
        '## Minimal example',
        example ? jsonBlock(example) : '',
        '## Schema',
        '',
        `Download: ${markdownSchemaLink(manifest.doc)}`
    ].filter(Boolean).join('\n')
}

export function extractSdkDeclarations(sdkFilePath: string): SdkDeclaration[] {
    const source = readFileSync(sdkFilePath, 'utf8')
    const sourceFile = ts.createSourceFile(sdkFilePath, source, ts.ScriptTarget.Latest, true, ts.ScriptKind.TS)
    const declarations: SdkDeclaration[] = []

    for (const statement of sourceFile.statements) {
        if (!isExported(statement)) continue
        if (!ts.isTypeAliasDeclaration(statement) && !ts.isInterfaceDeclaration(statement)) continue
        const name = statement.name.text
        const kind = ts.isInterfaceDeclaration(statement) ? 'interface' : 'type'
        const summary = getJsDocSummary(source, statement) || 'Public plugin SDK type.'
        declarations.push({
            name,
            kind,
            summary,
            source: source.slice(statement.getStart(sourceFile), statement.end)
        })
    }

    return declarations
}

function isExported(node: ts.Node): boolean {
    return Boolean(ts.getCombinedModifierFlags(node as ts.Declaration) & ts.ModifierFlags.Export)
}

function getJsDocSummary(source: string, node: ts.Node): string {
    const ranges = ts.getLeadingCommentRanges(source, node.pos) ?? []
    const jsDoc = ranges
        .map((range) => source.slice(range.pos, range.end))
        .find((comment) => comment.startsWith('/**'))
    if (!jsDoc) return ''
    return jsDoc
        .replace(/^\/\*\*/, '')
        .replace(/\*\/$/, '')
        .split('\n')
        .map((line) => line.replace(/^\s*\* ?/, '').trim())
        .filter(Boolean)
        .join(' ')
}

function renderDeclarationList(declarations: SdkDeclaration[], names: string[]): string {
    return names.map((name) => {
        const declaration = declarations.find((entry) => entry.name === name)
        if (!declaration) return `### ${name}\n\n_Missing from generated SDK declarations._\n`
        return [`### ${declaration.name}`, '', declaration.summary, tsBlock(declaration.source)].join('\n')
    }).join('\n')
}

function renderSchemaBrief(input: SchemaRenderInput): string {
    return [
        `### ${input.doc.title}`,
        '',
        input.doc.description,
        '',
        `JSON Schema: ${markdownSchemaLink(input.doc)}`,
        '',
        renderPropertiesTable(input, '#### Top-level fields')
    ].join('\n')
}

export function renderRuntimesPage(inputs: SchemaRenderInput[], declarations: SdkDeclaration[]): string {
    const schemaNames = [
        'PluginNotificationEvent',
        'RunnerSpawnOptionsContext',
        'RunnerSpawnOptionsProviderProposal',
        'RunnerResolvedSpawnOptions',
        'RunnerSpawnContext',
        'RunnerEnvironmentProposal',
        'RunnerCommandResolverProposal',
        'RunnerSpawnHookProposal',
        'RunnerResolvedSpawnPlan',
        'AgentDescriptor',
        'AgentCapabilityProviderResult',
        'AgentCapabilityProviderSnapshot',
        'AgentHistoryImportResult'
    ]
    return GENERATED_HEADER + [
        '# Plugin runtimes',
        '',
        'Runtime plugins run as trusted local in-process JavaScript. Hub and Runner expose narrow registration APIs; core keeps auth, namespace, persistence, transport, and final session lifecycle control.',
        tsBlock("import type { HubPluginContext, RunnerPluginContext } from '@hapi/protocol/plugins'"),
        '## Common primitives',
        renderDeclarationList(declarations, [
            'MaybePromise',
            'Disposable',
            'PluginLogger',
            'PluginConfigReader',
            'PluginSecretReader'
        ]),
        '## Hub runtime',
        '',
        'Hub plugins can register notification channels and chat composer message-action planners. They do not receive raw Hub internals.',
        renderDeclarationList(declarations, [
            'HubPluginContext',
            'PluginNotificationChannel',
            'HubMessageActionContribution',
            'HubMessageActionInput',
            'HubMessageActionResult',
            'MessageSendPlan',
            'HubPluginModule'
        ]),
        '## Runner runtime',
        '',
        'Runner plugins can propose spawn defaults, environment patches, command args, spawn hooks, agent adapters, capability providers, and generic runner actions. Proposals are schema-validated and audited before core applies them.',
        renderDeclarationList(declarations, [
            'RunnerPluginContext',
            'RunnerSpawnOptionsProviderContribution',
            'RunnerEnvironmentProviderContribution',
            'RunnerCommandResolverContribution',
            'RunnerSpawnHookContribution',
            'RunnerPluginActionContribution',
            'RunnerPluginActionInput',
            'RunnerPluginActionResult'
        ]),
        '## Agent extensions',
        '',
        'Agent adapters and capability providers execute in the Runner runtime. Hub and Web consume validated descriptors and snapshots.',
        renderDeclarationList(declarations, [
            'RunnerAgentAdapterContribution',
            'RunnerAgentCapabilityProviderContribution',
            'AgentBackend',
            'AgentBackendFactory',
            'AgentMessage',
            'PermissionRequest',
            'PermissionResponse'
        ]),
        '## Runtime DTO schemas',
        '',
        ...schemaNames.map((name) => renderSchemaBrief(requireSchemaInput(inputs, name)))
    ].join('\n')
}

export function renderWebDescriptorsPage(inputs: SchemaRenderInput[]): string {
    const web = requireSchemaInput(inputs, 'PluginWebContributions')
    const example = bundledExamplePlugins.find((plugin) => plugin.manifest.contributions?.web)?.manifest.contributions?.web
    return GENERATED_HEADER + [
        '# Web descriptors',
        '',
        'Web contributions are declarative JSON descriptors. The Web app renders built-in components only and never executes plugin JavaScript.',
        '',
        `JSON Schema: ${markdownSchemaLink(web.doc)}`,
        '',
        '## Contribution groups',
        '',
        '| Group | Rendered surface | Notes |',
        '|---|---|---|',
        '| `settingsPanels` | Settings → Plugins detail | Components: text, badge, table, actionButton, schemaForm, runnerSpawnDefaultsEditor |',
        '| `newSessionFields` | New Session form | text, number, boolean, select |',
        '| `actions` / `badges` | Plugin detail metadata | Core plugin-management actions only |',
        '| `composerActions` | Chat composer | `pluginMessageAction` routed to Hub or Runner action handlers |',
        '',
        '## Form fields',
        '',
        '- `schemaForm` fields support `text`, `number`, `boolean`, `select`, and `multiSelect`.',
        '- `select` / `multiSelect` may use static `options` or an `optionsSource` such as `notification.agents` or `runner.models`.',
        '- `secret: true` fields are redacted; secret values must still come from runtime environment variables.',
        '',
        '## Example',
        example ? jsonBlock(example) : ''
    ].filter(Boolean).join('\n')
}

function queryParams(endpoint: EndpointDoc): EndpointQueryParamDoc[] {
    return [
        ...(endpoint.targetQuery ? [{ name: 'target', description: 'Plugin target scope.', schemaRef: 'PluginTargetScope' }] : []),
        ...(endpoint.queryParams ?? [])
    ]
}

function queryNames(endpoint: EndpointDoc): string {
    const names = queryParams(endpoint).map((entry) => `\`${entry.name}\``)
    return names.length > 0 ? names.join(', ') : '—'
}

export function renderAdminApiPage(endpoints: EndpointDoc[]): string {
    const rows = endpoints.map((endpoint) => {
        const body = endpoint.bodySchema ? `\`${endpoint.bodySchema}\`` : '—'
        return `| \`${endpoint.method}\` | \`${endpoint.path}\` | ${queryNames(endpoint)} | ${body} | \`${endpoint.responseSchema}\` | ${endpoint.description} |`
    })
    return GENERATED_HEADER + [
        '# Plugin admin API',
        '',
        'Authenticated HAPI Web API endpoints for plugin management. `target` accepts `hub`, `runner:<machineId>`, or `all-runners` where supported.',
        '',
        'OpenAPI JSON: [/docs/plugin-api/openapi.json](/docs/plugin-api/openapi.json)',
        '',
        '| Method | Path | Query | Body | Response | Notes |',
        '|---|---|---|---|---|---|',
        ...rows,
        '',
        '## Target semantics',
        '',
        '- `hub`: operate on the Hub process and Hub-local plugin directory.',
        '- `runner:<machineId>`: operate through target-scoped Runner RPC; Hub does not read or write Runner plugin files directly.',
        '- `all-runners`: fan out supported operations to all Runner machines in the namespace.'
    ].join('\n')
}

export function renderMarketplacePage(inputs: SchemaRenderInput[]): string {
    return GENERATED_HEADER + [
        '# Plugin marketplace',
        '',
        'The marketplace is a static metadata catalog. Plugin packages stay in plugin authors\' GitHub Releases; HAPI validates catalog metadata and downloaded package checksums before planning installation.',
        '',
        '## User flow',
        '',
        '1. Browse entries through Web Settings or `hapi plugins marketplace list`.',
        '2. Create an install plan for a release.',
        '3. Review Hub/Runner target compatibility, conflicts, and offline skips.',
        '4. Execute the plan. Hub installs Hub/Web parts and distributes Runner parts via Runner RPC.',
        '',
        '## Developer flow',
        '',
        shellBlock(`bun run marketplace:validate
bun run marketplace:check`),
        '',
        'Package rules:',
        '',
        '- Publish `.tgz` or `.zip` assets from the plugin repository release.',
        '- Include `hapi.plugin.json` and `hapi.plugin.package.json` in the package.',
        '- Record `sha256:<64 hex>` checksum in `marketplace/catalog.v1.json`.',
        '- Do not commit installable plugin archives or plugin source trees under `marketplace/`.',
        '',
        '## Schemas',
        '',
        `- Catalog: ${schemaLinkByTitle(inputs, 'PluginMarketplaceCatalog')}`,
        `- List response: ${schemaLinkByTitle(inputs, 'PluginMarketplaceListResponse')}`,
        `- Detail response: ${schemaLinkByTitle(inputs, 'PluginMarketplaceDetailResponse')}`,
        `- Install request: ${schemaLinkByTitle(inputs, 'PluginMarketplaceInstallRequest')}`,
        `- Install-plan response: ${schemaLinkByTitle(inputs, 'PluginMarketplaceInstallPlanResponse')}`
    ].join('\n')
}

function requireSchemaInput(inputs: SchemaRenderInput[], title: string): SchemaRenderInput {
    const match = inputs.find((input) => input.doc.title === title)
    if (!match) {
        throw new Error(`Missing schema render input: ${title}`)
    }
    return match
}

export function schemaGroupLabel(group: SchemaGroup): string {
    return groupLabels[group]
}
